const English = {
    sp: 'Similar Products',
    kwd: 'KWD',
    dsc: 'Description',
    atc: 'Add To Cart',
    c: 'Count',
    so: 'Sold Out',
    b: 'Bulding',
    aby: ' a better you',
    aocb: 'Anyone can beat you but no one can beat your',
    oala: ' outfit as long as you wear Eestasy outfits .',
    sn: 'Start Now',
    cat: 'CATEGORIES',
    nea: 'NEW ARRIVAL',
    cu: 'CONTACT US',
    fn: 'Full Name',
    e: 'E-Mail',
    ym: "Your Message ...",
    s: 'Send',
    jon: 'JOIN OUR NEWSLETTER',
    sub: 'Subscribe',
    au: 'ABOUT US',
    pp: 'PRIVACY POLICY',
    tou: 'Term Of Use',
    faq: 'FAQ',
    cc: 'CUSTOMER CARE',
    sar: 'SHIPPING & RETURNS',
    ice: 'INFO CENTER',
    ywl: 'YOU WILL LOVE US FOR',
    qp: 'Quality Products',
    fsw: 'Free Sample with Every Order',
    fsh: 'Fast Shipping & Handling',
    rcs: 'Reliable Customer Service',
    en: 'English',
    ar: 'Arablic',
    h: 'HOME',
    n: 'NEW',
    o: 'OFFERS',
    mp: 'My Profile',
    ma: 'My Address',
    mo: 'My Orders',
    mf: 'My Favorites',
    cp: 'Change Password',
    lo: 'Log Out',
    li: 'Login',
    su: 'Sign Up',
    sot: 'Sort Type',
    name: 'Name',
    p: 'Price',
    up: 'Update',
    ana: 'Add New Address',
    da: 'Delivery Address',
    de: 'Default',
    ari: 'Area ',
    st: 'Street ',
    ho: 'House ',
    al: 'All',
    ip: 'In Progress',
    od: 'On Delivery',
    com: 'Completed',
    oi: 'Order Id',
    ch: 'Change',
    op: 'Old Password',
    np: 'New Password',
    det: 'Details',
    sc: 'SHOPPING CART',
    os: 'Order Summary',
    spr: 'Sub Price',
    si: 'Shipping',
    di: 'Discount',
    tp: 'Total Price',
    pc: 'Promo Code',
    ad: 'ADD',
    co: 'Checkout',
    ic: 'Invalid Code',
    vc: 'Valid Code',
    g: 'Guest',
    us: 'User',
    mal: 'MY ACCOUNT LOGIN',
    log: 'LOGIN',
    ca: 'CREATE ACCOUNT',
    pass: 'Password',
    rem: 'Remember me?',
    for: 'Forgot Bassword?',
    sig: 'SIGN IN',
    conpass: 'Confirm Password',
    snup: 'SIGN UP',
    sipa: 'SHIPPING ADDRESS',
    ych: 'You currently have no saved addresses.',
    adna: 'Add New Address',
    rvo: 'Review Orders',
    pon: 'Phone Number',
    atd: 'Address Title (Default)',
    adrs: 'Address',
    conf: 'Confirm',
    sadd: 'Select available delivery date / time:',
    uo: 'Your Order ',
    hba: 'Has Been Accepted',
    yihb: 'Your item has been placed and is on ',
    iwtb: ' its way to being processed',
    bth: 'Back To Home',
    searchHealperText: "Sorry to say, But we don't have the product you are looking for.",
    ord: 'ORDER DETAILS',
    dor: 'Date of receipt',
    tor: 'Time of receipt',
    cht: 'This category does not contain any products yet !',
    ydus: 'Your Data Updated Successfully',
    city: 'city',
    nsa: 'NEW SHIPPING ADDRESS',
    usa: 'UPDATE SHIPPING ADDRESS',
    yhaa: "You haven't added any address yet",
    yhaf: "You haven't added any favourite products yet",
    dywt: "Do You Want To Proceed To Checkout As?",
    adtm: "Available delivery date/time must be after:",
    uya: "Update Your Address",
}

export default English;